/**
 * Vercel build: writes config-runtime.js from RAILWAY_API_BASE_URL.
 * Set in Vercel → Project → Settings → Environment Variables:
 *   RAILWAY_API_BASE_URL = https://你的服务.up.railway.app   (不要 /api 结尾)
 */
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, "..");
const outFile = path.join(root, "config-runtime.js");

const raw = (process.env.RAILWAY_API_BASE_URL || "").trim();
if (!raw) {
  console.warn(
    "[vercel-build] RAILWAY_API_BASE_URL is empty — config-runtime.js will be stub. Set RAILWAY_API_BASE_URL in Vercel for production API."
  );
  fs.writeFileSync(
    outFile,
    "// Stub for local / missing env. Vercel: set RAILWAY_API_BASE_URL and redeploy.\nwindow.EDUTECH_API_BASE_URL = \"\";\n",
    "utf8"
  );
  process.exit(0);
}

let base = raw.replace(/\/+$/, "");
if (base.toLowerCase().endsWith("/api")) {
  base = base.slice(0, -4);
}
const apiBase = `${base}/api`;
const js = `// Generated by scripts/vercel-build.mjs — do not edit by hand on Vercel\nwindow.EDUTECH_API_BASE_URL = ${JSON.stringify(apiBase)};\n`;
fs.writeFileSync(outFile, js, "utf8");
console.log("[vercel-build] wrote config-runtime.js →", apiBase);
